package auctionframework;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 * GUI panel of a participant agent.
 */
public class ParticipantPanel extends javax.swing.JPanel {
    // The agent the panel belongs to
    private AbstractAgent participant;
    
    // The auction the panel belongs to
    private Auction auction;
    
    // The list items displayed in this panel
    private HashMap<AuctionItem, JPanel> itemPanels = new HashMap<AuctionItem, JPanel>();
    
    /**
     * Creates new form ParticipantPanel.
     */
    public ParticipantPanel() {
        initComponents();
    }
    
    /**
     * Constructor.
     * 
     * @param a         The auction the panel belongs to
     * @param p         The agent the panel belongs to
     */
    public ParticipantPanel(Auction a, AbstractAgent p) {
        initComponents();
        
        // Set custom layout
        jPanel2.setLayout(new WrapLayout());
        jPanel2.setMaximumSize(jPanel2.getSize());
        
        // Save properties
        this.auction = a;
        this.participant = p;
        
        // Update GUI
        updatePanel();
    }
    
    /**
     * Update the GUI elements
     */
    public void updatePanel() {
        // Update the name field
        String name = participant.getName();
        if (AuctionFramework.auction != null) {
            String color = "black";
            int state = participant.getState();
            if (state == 0) color = "gray";
            else if (state == 1) color = "red";
            else if (state == 2) color = "green";
            name = "<html><span color='"+color+"'>"+name+"</span></html>";
        }
        jLabel1.setText(name);
        
        // Update the money field
        jLabel3.setText(String.format("%,d", participant.getMoney())+" money");
        
        // Display all owner item
        ArrayList<AuctionItem> items = participant.getItems();
        for (int i=0; i<items.size(); i++) {
            AuctionItem item = items.get(i);
            if (itemPanels.get(item) == null) {
                JPanel panel = new JPanel();
                
                // Calculate color based on the utility value of the item
                float n = item.getUtility();
                if (n>1) n=1;
                
                float red = 0, green = 0;
                if (0<=n && n<0.5) {        
                    green = 1;
                    red = 2 * n;
                }
                if (0.5<=n && n<=1) {       
                    red = 1;
                    green = 1 - 2 * (n-0.5f);
                }
                
                panel.setBackground(new Color(red, green , 0));
                panel.setSize(30, 30);
                panel.setToolTipText("<html>"+item.getName()+"<br>"+String.format("%,d", item.getPrice())+" price (started from "+String.format("%,d", item.getStartingPrice())+") -> "+String.format("%,d", Math.round(item.getUtility()*100))+"% price increase</html>");
                jPanel2.add(panel);
                itemPanels.put(item,panel);
                
                // Update the efficiency panel
                jLabel2.setText(String.format("%,d", Math.round(participant.getTotalEfficiency()))+" % eff.");
                
                // Update the fortune panel
                jLabel4.setText(String.format("%,d", participant.getTotalStartingPrice())+" fort.");
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("ParticipantName");

        jLabel2.setText("eff.");

        jLabel3.setText(" money");

        jLabel4.setText("total fortune");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
